import { Geist, Geist_Mono, Montserrat } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "./components/Header";

const montserrat = Montserrat({
  subsets: ['latin']
})



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">

        <head>
            <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
            new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
            j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
            'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
            })(window,document,'script','dataLayer','GTM-PSTHNMR3');</script>
        </head>
        
        <body className={`${montserrat.className} antialiased`}>

          <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-PSTHNMR3"
          height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>

          <Header />
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}
